repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.9
  hooks:
    # Run the linter.
    - id: ruff
      args: ["--fix"]
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks:
    - id: ty
      name: ty type checker
      entry: ty check
      language: system
      types: [python]
      pass_filenames: false
