version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/app:delegated
    environment:
      - PYTHONUNBUFFERED=1 
    command: ["uv", "run", "fastapi", "dev", "app/main.py",  "--port", "80"]